version: '3'
services:
  db:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
#    deploy:
#      resources:
#        limits:
#          cpus: '0.001'
#          memory: 500M
    volumes:
      - ./data/virtuoso:/data
    ports:
      - "8891:8891"
  loadtester:
    build: .
